# Bước 15 – Lần chạy chốt: 5 hạt giống ngẫu nhiên, khoảng tin cậy, kiểm định thống kê

Đây là lần chạy cho SỐ LIỆU CUỐI CÙNG của bài báo. Cấu hình đã chốt (không chỉnh thêm):
- 3 loại mô hình: LightGBM, MLP, cây quyết định;
- hướng 1 (không nhãn): trung bình đều, chọn theo kiểm định nguồn, TADP, CORAL, Isolation Forest, tự huấn luyện, nhãn giả đồng thuận;
- hướng 2: M2 với 100 / 500 / 1.000 / 5.000 nhãn thật, bốc 3 lần;
- mốc đủ nhãn;
- ngưỡng: cố định (a), Otsu có chặn (e), chống sập 5 / 10 / 20% (h10 là cách chính).

Lý thuyết (khoảng tin cậy, kiểm định Wilcoxon, kèm ví dụ số) ở Phần 7 của tài liệu "TADP-IDS – Lý thuyết bước 13".

| Ô | Việc | Thời gian |
|---|---|---|
| 1 | Kiểm tra môi trường và mã nguồn | 1 phút |
| 2 | Chạy 5 hạt giống × 3 loại mô hình × 4 mạng | khoảng 4–6 giờ tổng cộng |
| 3 | Tổng hợp + kiểm định (chạy được bất cứ lúc nào) | 1 phút |

**Dùng máy CPU, không GPU** (Runtime → Change runtime type → CPU). Kết quả lưu vào `MyDrive/TADP_Q1/results/b15_chot/`.

**Nếu Colab ngắt giữa chừng:** mở lại notebook, chạy lại Ô 1 rồi Ô 2 – phần nào xong rồi (hạt giống, loại mô hình, mạng) sẽ được bỏ qua, chạy tiếp từ chỗ dừng. Có thể chạy làm nhiều buổi.

## Ô 1 – Kiểm tra môi trường và mã nguồn

In [2]:
import os, sys, subprocess
from google.colab import drive
drive.mount("/content/drive")
CODE_DIR = "/content/drive/MyDrive/TADP_Q1/code"
sys.path.insert(0, CODE_DIR)
for m in [k for k in sys.modules if k.startswith("tadp")]:
    del sys.modules[m]
try:
    import lightgbm, pyarrow
except ImportError:
    subprocess.run([sys.executable, "-m", "pip", "install", "-q", "lightgbm", "pyarrow"], check=True)
import torch
print("GPU:", "CÓ – nên đổi sang CPU" if torch.cuda.is_available() else "không có (đúng như mong muốn)")
EXPECTED = {"__init__.py": 125, "cic_data.py": 8579, "config.py": 3263, "data.py": 9956, "experts.py": 5934,
            "few_label.py": 15932, "final_run.py": 18041, "label_free.py": 16327, "metrics.py": 4002,
            "model_families.py": 10460, "preprocess.py": 3601, "shift.py": 3863, "window_threshold.py": 12240}
ok = True
for f, size in EXPECTED.items():
    p = os.path.join(CODE_DIR, "tadp", f)
    real = os.path.getsize(p) if os.path.exists(p) else None
    if real != size:
        ok = False
        print(f"   SAI: {f} – mong đợi {size} byte, thực tế {real}")
print("Mã nguồn:", "ĐẦY ĐỦ, đúng phiên bản bước 15" if ok else "CÓ LỖI – báo lại cho Claude")

Mounted at /content/drive
GPU: không có (đúng như mong muốn)
Mã nguồn: ĐẦY ĐỦ, đúng phiên bản bước 15

## Ô 2 – Chạy (dài)

In lần lượt "[hạt giống …] [loại mô hình] 4 chuyên gia nguồn xong", rồi "[hạt giống …] [loại mô hình] [tên mạng] xong trong … giây". Tổng cộng 5 × 3 × 4 = 60 dòng "xong". Chạy xong toàn bộ thì in luôn các bảng tổng hợp.

In [3]:
import sys, warnings
warnings.filterwarnings("ignore")
from google.colab import drive
drive.mount("/content/drive")
sys.path.insert(0, "/content/drive/MyDrive/TADP_Q1/code")
for m in [k for k in sys.modules if k.startswith("tadp")]:
    del sys.modules[m]
from tadp.config import get_config
from tadp.data import load_all, make_splits, common_features
from tadp.final_run import run_final
B = "/content/drive/MyDrive/TADP_Q1"
DOMAINS_CIC = {"CIC-IDS2017": ["2017"], "CSE-CIC-IDS2018": ["2018"], "CIC-ToN-IoT": ["ton"], "CIC-UNSW-NB15": ["unsw"]}
cfg = get_config(RAW_DIR=f"{B}/raw_cic", CACHE_DIR=f"{B}/cache_cic", RESULT_DIR=f"{B}/results/b15_chot",
                 DOMAINS=DOMAINS_CIC, SPLIT_MODE="episode", LGBM_ROUNDS=200)
data = load_all(cfg)
splits, _ = make_splits(cfg, data)
cols = common_features(data, "no_id")
run_final(cfg, data, splits, cols, pv="P1_log")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
CIC-IDS2017: 999,712 dòng, 87 cột, tỷ lệ tấn công = 0.2411
CSE-CIC-IDS2018: 999,829 dòng, 87 cột, tỷ lệ tấn công = 0.0559
CIC-ToN-IoT: 1,000,028 dòng, 82 cột, tỷ lệ tấn công = 0.5302
CIC-UNSW-NB15: 1,000,399 dòng, 82 cột, tỷ lệ tấn công = 0.0251
[hạt giống 11] [lgbm] 4 chuyên gia nguồn xong (93 giây)
[hạt giống 11] [lgbm] [CIC-IDS2017] xong trong 375 giây
[hạt giống 11] [lgbm] [CSE-CIC-IDS2018] xong trong 386 giây
[hạt giống 11] [lgbm] [CIC-ToN-IoT] xong trong 377 giây
[hạt giống 11] [lgbm] [CIC-UNSW-NB15] xong trong 370 giây
[hạt giống 11] [mlp] 4 chuyên gia nguồn xong (103 giây)
[hạt giống 11] [mlp] [CIC-IDS2017] xong trong 293 giây
[hạt giống 11] [mlp] [CSE-CIC-IDS2018] xong trong 336 giây
[hạt giống 11] [mlp] [CIC-ToN-IoT] xong trong 338 giây
[hạt giống 11] [mlp] [CIC-UNSW-NB15] xong trong 448 giây
[hạt giống 11] [tree] 4 chuyên gia nguồn xong (50 giây)
[hạt giống 11] [tree] [CIC-IDS2017] xong trong 225 giây
[hạt giống 11] [tree] [CSE-CIC-IDS2018] xong trong 244 giây
[hạt giống 11] [tree] [CIC-ToN-IoT] xong trong 240 giây
[hạt giống 11] [tree] [CIC-UNSW-NB15] xong trong 248 giây
[hạt giống 22] [lgbm] 4 chuyên gia nguồn xong (89 giây)
[hạt giống 22] [lgbm] [CIC-IDS2017] xong trong 371 giây
[hạt giống 22] [lgbm] [CSE-CIC-IDS2018] xong trong 388 giây
[hạt giống 22] [lgbm] [CIC-ToN-IoT] xong trong 378 giây
[hạt giống 22] [lgbm] [CIC-UNSW-NB15] xong trong 361 giây
[hạt giống 22] [mlp] 4 chuyên gia nguồn xong (88 giây)
[hạt giống 22] [mlp] [CIC-IDS2017] xong trong 321 giây
[hạt giống 22] [mlp] [CSE-CIC-IDS2018] xong trong 379 giây
[hạt giống 22] [mlp] [CIC-ToN-IoT] xong trong 354 giây
[hạt giống 22] [mlp] [CIC-UNSW-NB15] xong trong 402 giây
[hạt giống 22] [tree] 4 chuyên gia nguồn xong (49 giây)
[hạt giống 22] [tree] [CIC-IDS2017] xong trong 240 giây
[hạt giống 22] [tree] [CSE-CIC-IDS2018] xong trong 248 giây
[hạt giống 22] [tree] [CIC-ToN-IoT] xong trong 256 giây
[hạt giống 22] [tree] [CIC-UNSW-NB15] xong trong 250 giây
[hạt giống 33] [lgbm] 4 chuyên gia nguồn xong (90 giây)
[hạt giống 33] [lgbm] [CIC-IDS2017] xong trong 374 giây
[hạt giống 33] [lgbm] [CSE-CIC-IDS2018] xong trong 394 giây
[hạt giống 33] [lgbm] [CIC-ToN-IoT] xong trong 385 giây
[hạt giống 33] [lgbm] [CIC-UNSW-NB15] xong trong 380 giây
[hạt giống 33] [mlp] 4 chuyên gia nguồn xong (100 giây)
[hạt giống 33] [mlp] [CIC-IDS2017] xong trong 316 giây
[hạt giống 33] [mlp] [CSE-CIC-IDS2018] xong trong 369 giây
[hạt giống 33] [mlp] [CIC-ToN-IoT] xong trong 378 giây
[hạt giống 33] [mlp] [CIC-UNSW-NB15] xong trong 431 giây
[hạt giống 33] [tree] 4 chuyên gia nguồn xong (52 giây)
[hạt giống 33] [tree] [CIC-IDS2017] xong trong 246 giây
[hạt giống 33] [tree] [CSE-CIC-IDS2018] xong trong 252 giây
[hạt giống 33] [tree] [CIC-ToN-IoT] xong trong 251 giây
[hạt giống 33] [tree] [CIC-UNSW-NB15] xong trong 257 giây
[hạt giống 44] [lgbm] 4 chuyên gia nguồn xong (92 giây)
[hạt giống 44] [lgbm] [CIC-IDS2017] xong trong 383 giây
[hạt giống 44] [lgbm] [CSE-CIC-IDS2018] xong trong 411 giây
[hạt giống 44] [lgbm] [CIC-ToN-IoT] xong trong 386 giây
[hạt giống 44] [lgbm] [CIC-UNSW-NB15] xong trong 375 giây
[hạt giống 44] [mlp] 4 chuyên gia nguồn xong (104 giây)
[hạt giống 44] [mlp] [CIC-IDS2017] xong trong 397 giây
[hạt giống 44] [mlp] [CSE-CIC-IDS2018] xong trong 344 giây
[hạt giống 44] [mlp] [CIC-ToN-IoT] xong trong 401 giây
[hạt giống 44] [mlp] [CIC-UNSW-NB15] xong trong 457 giây
[hạt giống 44] [tree] 4 chuyên gia nguồn xong (53 giây)
[hạt giống 44] [tree] [CIC-IDS2017] xong trong 245 giây
[hạt giống 44] [tree] [CSE-CIC-IDS2018] xong trong 262 giây
[hạt giống 44] [tree] [CIC-ToN-IoT] xong trong 258 giây
[hạt giống 44] [tree] [CIC-UNSW-NB15] xong trong 261 giây
[hạt giống 55] [lgbm] 4 chuyên gia nguồn xong (99 giây)
[hạt giống 55] [lgbm] [CIC-IDS2017] xong trong 410 giây
[hạt giống 55] [lgbm] [CSE-CIC-IDS2018] xong trong 412 giây
[hạt giống 55] [lgbm] [CIC-ToN-IoT] xong trong 407 giây
[hạt giống 55] [lgbm] [CIC-UNSW-NB15] xong trong 399 giây
[hạt giống 55] [mlp] 4 chuyên gia nguồn xong (99 giây)
[hạt giống 55] [mlp] [CIC-IDS2017] xong trong 355 giây
[hạt giống 55] [mlp] [CSE-CIC-IDS2018] xong trong 408 giây
[hạt giống 55] [mlp] [CIC-ToN-IoT] xong trong 402 giây
[hạt giống 55] [mlp] [CIC-UNSW-NB15] xong trong 458 giây
[hạt giống 55] [tree] 4 chuyên gia nguồn xong (54 giây)
[hạt giống 55] [tree] [CIC-IDS2017] xong trong 252 giây
[hạt giống 55] [tree] [CSE-CIC-IDS2018] xong trong 245 giây
[hạt giống 55] [tree] [CIC-ToN-IoT] xong trong 253 giây
[hạt giống 55] [tree] [CIC-UNSW-NB15] xong trong 255 giây
Số hạt giống đã có: 5 ([np.int64(11), np.int64(22), np.int64(33), np.int64(44), np.int64(55)])

BẢNG 15.1 – Macro-F1 trung bình 4 mạng ± nửa khoảng tin cậy 95% (qua các hạt giống)
  a = ngưỡng cố định, h10 = chống sập 10% (cách chính); k = -1 là mốc đủ nhãn
 mo_hinh                                 lgbm                           mlp                          tree
cach_nguong                        a_co_dinh h_chong_sap_10      a_co_dinh h_chong_sap_10      a_co_dinh h_chong_sap_10
phuong_phap             k
CORAL                    0     0.443 ± 0.033  0.351 ± 0.042  0.413 ± 0.073  0.444 ± 0.055  0.440 ± 0.013  0.330 ± 0.039
DE_XUAT_dong_thuan       0     0.470 ± 0.025  0.471 ± 0.023  0.463 ± 0.066  0.476 ± 0.073  0.451 ± 0.027  0.466 ± 0.041
M2                       100   0.782 ± 0.057  0.785 ± 0.059  0.806 ± 0.019  0.799 ± 0.017  0.764 ± 0.035  0.773 ± 0.035
                         500   0.790 ± 0.020  0.826 ± 0.048  0.899 ± 0.007  0.895 ± 0.004  0.846 ± 0.031  0.819 ± 0.039
                         1000  0.840 ± 0.045  0.888 ± 0.041  0.917 ± 0.007  0.907 ± 0.004  0.807 ± 0.043  0.787 ± 0.054
                         5000  0.840 ± 0.029  0.922 ± 0.047  0.933 ± 0.004  0.918 ± 0.015  0.811 ± 0.020  0.797 ± 0.027
isolation_forest         0     0.473 ± 0.009  0.452 ± 0.041  0.473 ± 0.009  0.452 ± 0.041  0.473 ± 0.009  0.452 ± 0.041
k0_TADP                  0     0.505 ± 0.033  0.458 ± 0.034  0.558 ± 0.016  0.528 ± 0.045  0.500 ± 0.044  0.389 ± 0.069
k0_chon_kiem_dinh_nguon  0     0.499 ± 0.017  0.528 ± 0.052  0.550 ± 0.023  0.534 ± 0.038  0.540 ± 0.035  0.513 ± 0.047
k0_trung_binh_deu        0     0.447 ± 0.032  0.377 ± 0.031  0.495 ± 0.010  0.502 ± 0.039  0.441 ± 0.024  0.270 ± 0.095
tran_du_nhan            -1     0.971 ± 0.001  0.965 ± 0.008  0.960 ± 0.003  0.949 ± 0.003  0.965 ± 0.001  0.956 ± 0.001
tu_huan_luyen            0     0.519 ± 0.030  0.514 ± 0.028  0.534 ± 0.019  0.536 ± 0.020  0.443 ± 0.079  0.433 ± 0.075

BẢNG 15.2 – AUROC trung bình 4 mạng ± nửa khoảng tin cậy 95%
 mo_hinh                                 lgbm            mlp           tree
phuong_phap             k
CORAL                    0     0.529 ± 0.082  0.587 ± 0.061  0.575 ± 0.122
DE_XUAT_dong_thuan       0     0.588 ± 0.044  0.569 ± 0.078  0.559 ± 0.035
M2                       100   0.950 ± 0.011  0.903 ± 0.043  0.827 ± 0.040
                         500   0.980 ± 0.009  0.958 ± 0.016  0.932 ± 0.009
                         1000  0.989 ± 0.003  0.976 ± 0.006  0.932 ± 0.028
                         5000  0.995 ± 0.000  0.987 ± 0.001  0.880 ± 0.023
isolation_forest         0     0.685 ± 0.007  0.685 ± 0.007  0.685 ± 0.007
k0_TADP                  0     0.562 ± 0.037  0.553 ± 0.072  0.382 ± 0.059
k0_chon_kiem_dinh_nguon  0     0.561 ± 0.036  0.561 ± 0.047  0.564 ± 0.048
k0_trung_binh_deu        0     0.561 ± 0.019  0.524 ± 0.065  0.354 ± 0.060
tran_du_nhan            -1     0.998 ± 0.001  0.998 ± 0.000  0.997 ± 0.000
tu_huan_luyen            0     0.642 ± 0.023  0.580 ± 0.032  0.480 ± 0.102

BẢNG 15.3 – Kiểm định Wilcoxon: ngưỡng h10 so với ngưỡng cố định (M2)
  p_value < 0,05: chênh lệch khó là do may rủi
 mo_hinh    k  so_cap  trung_vi_chenh_lech  h10_hon  h10_kem  p_value
   lgbm  100      60               0.0000       15       18   0.9786
   lgbm  500      60               0.0001       30       29   0.3191
   lgbm 1000      60               0.0000       31       28   0.1273
   lgbm 5000      60              -0.0000       30       30   0.1152
    mlp  100      60               0.0000        6       25   0.0020
    mlp  500      60              -0.0020       19       37   0.0532
    mlp 1000      60              -0.0028       18       42   0.0008
    mlp 5000      60              -0.0017       20       40   0.0053
   tree  100      60               0.0000        7        7   0.3967
   tree  500      60               0.0000        5       29   0.0000
   tree 1000      60              -0.0051        5       33   0.0000
   tree 5000      60              -0.0072        7       44   0.0000

BẢNG 15.4 – Kiểm định Wilcoxon: M2 với k nhãn (h10) so với cách không nhãn tốt nhất
 mo_hinh     khong_nhan_tot_nhat    k  so_cap  trung_vi_chenh_lech  M2_hon  M2_kem  p_value
   lgbm k0_chon_kiem_dinh_nguon  100      20               0.2148      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon  500      20               0.2734      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon 1000      20               0.3950      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon 5000      20               0.4388      20       0      0.0
    mlp           tu_huan_luyen  100      20               0.2581      20       0      0.0
    mlp           tu_huan_luyen  500      20               0.3517      20       0      0.0
    mlp           tu_huan_luyen 1000      20               0.3783      20       0      0.0
    mlp           tu_huan_luyen 5000      20               0.3902      20       0      0.0
   tree k0_chon_kiem_dinh_nguon  100      20               0.2542      20       0      0.0
   tree k0_chon_kiem_dinh_nguon  500      20               0.2781      20       0      0.0
   tree k0_chon_kiem_dinh_nguon 1000      20               0.2594      20       0      0.0
   tree k0_chon_kiem_dinh_nguon 5000      20               0.2817      19       1      0.0

BẢNG 15.5 – Macro-F1 theo từng mạng (h10, trung bình các hạt giống)
 target                                 CIC-IDS2017  CIC-ToN-IoT  CIC-UNSW-NB15  CSE-CIC-IDS2018
mo_hinh phuong_phap             k
lgbm    CORAL                    0           0.355        0.384          0.360            0.304
        DE_XUAT_dong_thuan       0           0.578        0.423          0.496            0.388
        M2                       100         0.938        0.767          0.592            0.843
                                 500         0.971        0.600          0.785            0.950
                                 1000        0.979        0.797          0.813            0.964
                                 5000        0.991        0.882          0.837            0.976
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.685        0.375          0.390            0.384
        k0_chon_kiem_dinh_nguon  0           0.799        0.427          0.347            0.538
        k0_trung_binh_deu        0           0.486        0.388          0.313            0.323
        tran_du_nhan            -1           1.000        0.992          0.870            0.999
        tu_huan_luyen            0           0.720        0.387          0.515            0.435
mlp     CORAL                    0           0.671        0.377          0.347            0.381
        DE_XUAT_dong_thuan       0           0.554        0.601          0.362            0.386
        M2                       100         0.954        0.862          0.597            0.783
                                 500         0.974        0.935          0.754            0.916
                                 1000        0.982        0.937          0.794            0.914
                                 5000        0.988        0.956          0.819            0.907
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.730        0.497          0.438            0.446
        k0_chon_kiem_dinh_nguon  0           0.761        0.555          0.400            0.422
        k0_trung_binh_deu        0           0.659        0.463          0.438            0.447
        tran_du_nhan            -1           0.997        0.983          0.828            0.989
        tu_huan_luyen            0           0.753        0.590          0.363            0.436
tree    CORAL                    0           0.256        0.469          0.365            0.231
        DE_XUAT_dong_thuan       0           0.575        0.453          0.440            0.395
        M2                       100         0.919        0.764          0.580            0.828
                                 500         0.910        0.735          0.784            0.846
                                 1000        0.922        0.584          0.799            0.843
                                 5000        0.951        0.469          0.829            0.941
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.464        0.336          0.427            0.327
        k0_chon_kiem_dinh_nguon  0           0.698        0.395          0.401            0.557
        k0_trung_binh_deu        0           0.218        0.349          0.320            0.193
        tran_du_nhan            -1           0.994        0.988          0.849            0.991
        tu_huan_luyen            0           0.539        0.332          0.442            0.419

BẢNG 15.6 – Độ nhạy: Macro-F1 theo cách đặt ngưỡng (a, e, h05, h10, h20)
 cach_nguong                 a_co_dinh  e_otsu_cua_so_co_chan  h_chong_sap_05  h_chong_sap_10  h_chong_sap_20
mo_hinh phuong_phap  k
lgbm    M2            100       0.782                  0.789           0.786           0.785           0.782
                      500       0.790                  0.838           0.794           0.826           0.831
                      1000      0.840                  0.910           0.861           0.888           0.917
                      5000      0.840                  0.935           0.903           0.922           0.938
        tran_du_nhan -1         0.971                  0.854           0.965           0.965           0.965
mlp     M2            100       0.806                  0.779           0.804           0.799           0.797
                      500       0.899                  0.856           0.897           0.895           0.883
                      1000      0.917                  0.888           0.913           0.907           0.895
                      5000      0.933                  0.911           0.927           0.918           0.911
        tran_du_nhan -1         0.960                  0.949           0.949           0.949           0.949
tree    M2            100       0.764                  0.770           0.768           0.773           0.771
                      500       0.846                  0.845           0.836           0.819           0.815
                      1000      0.807                  0.820           0.796           0.787           0.775
                      5000      0.811                  0.805           0.802           0.797           0.823
        tran_du_nhan -1         0.965                  0.955           0.956           0.956           0.955

BẢNG 15.7 – Số lần M2 không học được (< 3 luồng của một lớp)
 mo_hinh  k    target
lgbm     100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2
mlp      100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2
tree     100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2

    mo_hinh              phuong_phap     k            cach_nguong  macro_f1  macro_f1_ci     auroc  auroc_ci              o             oa
0      lgbm                    CORAL     0              a_co_dinh  0.442615     0.032912  0.529081  0.082000  0.443 ± 0.033  0.529 ± 0.082
1      lgbm                    CORAL     0  e_otsu_cua_so_co_chan  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
2      lgbm                    CORAL     0         h_chong_sap_05  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
3      lgbm                    CORAL     0         h_chong_sap_10  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
4      lgbm                    CORAL     0         h_chong_sap_20  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
5      lgbm       DE_XUAT_dong_thuan     0              a_co_dinh  0.469573     0.025202  0.588361  0.044033  0.470 ± 0.025  0.588 ± 0.044
6      lgbm       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
7      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
8      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
9      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
10     lgbm                       M2   100              a_co_dinh  0.781625     0.056654  0.950019  0.011289  0.782 ± 0.057  0.950 ± 0.011
11     lgbm                       M2   100  e_otsu_cua_so_co_chan  0.788535     0.036946  0.950019  0.011289  0.789 ± 0.037  0.950 ± 0.011
12     lgbm                       M2   100         h_chong_sap_05  0.786247     0.054978  0.950019  0.011289  0.786 ± 0.055  0.950 ± 0.011
13     lgbm                       M2   100         h_chong_sap_10  0.784955     0.059032  0.950019  0.011289  0.785 ± 0.059  0.950 ± 0.011
14     lgbm                       M2   100         h_chong_sap_20  0.781771     0.057630  0.950019  0.011289  0.782 ± 0.058  0.950 ± 0.011
15     lgbm                       M2   500              a_co_dinh  0.790331     0.020056  0.979688  0.008789  0.790 ± 0.020  0.980 ± 0.009
16     lgbm                       M2   500  e_otsu_cua_so_co_chan  0.838291     0.066220  0.979688  0.008789  0.838 ± 0.066  0.980 ± 0.009
17     lgbm                       M2   500         h_chong_sap_05  0.794279     0.024298  0.979688  0.008789  0.794 ± 0.024  0.980 ± 0.009
18     lgbm                       M2   500         h_chong_sap_10  0.826411     0.047650  0.979688  0.008789  0.826 ± 0.048  0.980 ± 0.009
19     lgbm                       M2   500         h_chong_sap_20  0.830775     0.053787  0.979688  0.008789  0.831 ± 0.054  0.980 ± 0.009
20     lgbm                       M2  1000              a_co_dinh  0.840404     0.044615  0.989273  0.002548  0.840 ± 0.045  0.989 ± 0.003
21     lgbm                       M2  1000  e_otsu_cua_so_co_chan  0.909637     0.025759  0.989273  0.002548  0.910 ± 0.026  0.989 ± 0.003
22     lgbm                       M2  1000         h_chong_sap_05  0.861321     0.043337  0.989273  0.002548  0.861 ± 0.043  0.989 ± 0.003
23     lgbm                       M2  1000         h_chong_sap_10  0.888103     0.040608  0.989273  0.002548  0.888 ± 0.041  0.989 ± 0.003
24     lgbm                       M2  1000         h_chong_sap_20  0.916802     0.027822  0.989273  0.002548  0.917 ± 0.028  0.989 ± 0.003
25     lgbm                       M2  5000              a_co_dinh  0.840033     0.028780  0.994596  0.000325  0.840 ± 0.029  0.995 ± 0.000
26     lgbm                       M2  5000  e_otsu_cua_so_co_chan  0.934796     0.006572  0.994596  0.000325  0.935 ± 0.007  0.995 ± 0.000
27     lgbm                       M2  5000         h_chong_sap_05  0.903444     0.043384  0.994596  0.000325  0.903 ± 0.043  0.995 ± 0.000
28     lgbm                       M2  5000         h_chong_sap_10  0.921568     0.047103  0.994596  0.000325  0.922 ± 0.047  0.995 ± 0.000
29     lgbm                       M2  5000         h_chong_sap_20  0.938382     0.005630  0.994596  0.000325  0.938 ± 0.006  0.995 ± 0.000
30     lgbm         isolation_forest     0              a_co_dinh  0.473199     0.009140  0.684869  0.006648  0.473 ± 0.009  0.685 ± 0.007
31     lgbm         isolation_forest     0  e_otsu_cua_so_co_chan  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
32     lgbm         isolation_forest     0         h_chong_sap_05  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
33     lgbm         isolation_forest     0         h_chong_sap_10  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
34     lgbm         isolation_forest     0         h_chong_sap_20  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
35     lgbm                  k0_TADP     0              a_co_dinh  0.505021     0.032541  0.561930  0.036822  0.505 ± 0.033  0.562 ± 0.037
36     lgbm                  k0_TADP     0  e_otsu_cua_so_co_chan  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
37     lgbm                  k0_TADP     0         h_chong_sap_05  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
38     lgbm                  k0_TADP     0         h_chong_sap_10  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
39     lgbm                  k0_TADP     0         h_chong_sap_20  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
40     lgbm  k0_chon_kiem_dinh_nguon     0              a_co_dinh  0.498551     0.017400  0.561417  0.036276  0.499 ± 0.017  0.561 ± 0.036
41     lgbm  k0_chon_kiem_dinh_nguon     0  e_otsu_cua_so_co_chan  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
42     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_05  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
43     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_10  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
44     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_20  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
45     lgbm        k0_trung_binh_deu     0              a_co_dinh  0.447383     0.031663  0.560953  0.019297  0.447 ± 0.032  0.561 ± 0.019
46     lgbm        k0_trung_binh_deu     0  e_otsu_cua_so_co_chan  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
47     lgbm        k0_trung_binh_deu     0         h_chong_sap_05  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
48     lgbm        k0_trung_binh_deu     0         h_chong_sap_10  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
49     lgbm        k0_trung_binh_deu     0         h_chong_sap_20  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
50     lgbm             tran_du_nhan    -1              a_co_dinh  0.970539     0.000602  0.998259  0.000590  0.971 ± 0.001  0.998 ± 0.001
51     lgbm             tran_du_nhan    -1  e_otsu_cua_so_co_chan  0.853685     0.119842  0.998259  0.000590  0.854 ± 0.120  0.998 ± 0.001
52     lgbm             tran_du_nhan    -1         h_chong_sap_05  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
53     lgbm             tran_du_nhan    -1         h_chong_sap_10  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
54     lgbm             tran_du_nhan    -1         h_chong_sap_20  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
55     lgbm            tu_huan_luyen     0              a_co_dinh  0.518978     0.029518  0.642075  0.023058  0.519 ± 0.030  0.642 ± 0.023
56     lgbm            tu_huan_luyen     0  e_otsu_cua_so_co_chan  0.514204     0.027782  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
57     lgbm            tu_huan_luyen     0         h_chong_sap_05  0.514220     0.027800  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
58     lgbm            tu_huan_luyen     0         h_chong_sap_10  0.514231     0.027815  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
59     lgbm            tu_huan_luyen     0         h_chong_sap_20  0.514204     0.027782  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
60      mlp                    CORAL     0              a_co_dinh  0.412621     0.073005  0.586801  0.060634  0.413 ± 0.073  0.587 ± 0.061
61      mlp                    CORAL     0  e_otsu_cua_so_co_chan  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
62      mlp                    CORAL     0         h_chong_sap_05  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
63      mlp                    CORAL     0         h_chong_sap_10  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
64      mlp                    CORAL     0         h_chong_sap_20  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
65      mlp       DE_XUAT_dong_thuan     0              a_co_dinh  0.462725     0.065899  0.568898  0.078224  0.463 ± 0.066  0.569 ± 0.078
66      mlp       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
67      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
68      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
69      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
70      mlp                       M2   100              a_co_dinh  0.806449     0.018885  0.903011  0.042607  0.806 ± 0.019  0.903 ± 0.043
71      mlp                       M2   100  e_otsu_cua_so_co_chan  0.778620     0.024352  0.903011  0.042607  0.779 ± 0.024  0.903 ± 0.043
72      mlp                       M2   100         h_chong_sap_05  0.804044     0.019321  0.903011  0.042607  0.804 ± 0.019  0.903 ± 0.043
73      mlp                       M2   100         h_chong_sap_10  0.799010     0.017103  0.903011  0.042607  0.799 ± 0.017  0.903 ± 0.043
74      mlp                       M2   100         h_chong_sap_20  0.797178     0.017553  0.903011  0.042607  0.797 ± 0.018  0.903 ± 0.043
75      mlp                       M2   500              a_co_dinh  0.898829     0.006687  0.957597  0.015985  0.899 ± 0.007  0.958 ± 0.016
76      mlp                       M2   500  e_otsu_cua_so_co_chan  0.856481     0.022044  0.957597  0.015985  0.856 ± 0.022  0.958 ± 0.016
77      mlp                       M2   500         h_chong_sap_05  0.896664     0.004713  0.957597  0.015985  0.897 ± 0.005  0.958 ± 0.016
78      mlp                       M2   500         h_chong_sap_10  0.894764     0.004496  0.957597  0.015985  0.895 ± 0.004  0.958 ± 0.016
79      mlp                       M2   500         h_chong_sap_20  0.883297     0.018366  0.957597  0.015985  0.883 ± 0.018  0.958 ± 0.016
80      mlp                       M2  1000              a_co_dinh  0.917136     0.006507  0.976010  0.005865  0.917 ± 0.007  0.976 ± 0.006
81      mlp                       M2  1000  e_otsu_cua_so_co_chan  0.887949     0.015345  0.976010  0.005865  0.888 ± 0.015  0.976 ± 0.006
82      mlp                       M2  1000         h_chong_sap_05  0.913403     0.006309  0.976010  0.005865  0.913 ± 0.006  0.976 ± 0.006
83      mlp                       M2  1000         h_chong_sap_10  0.906826     0.003890  0.976010  0.005865  0.907 ± 0.004  0.976 ± 0.006
84      mlp                       M2  1000         h_chong_sap_20  0.894816     0.016606  0.976010  0.005865  0.895 ± 0.017  0.976 ± 0.006
85      mlp                       M2  5000              a_co_dinh  0.933137     0.004405  0.987329  0.001484  0.933 ± 0.004  0.987 ± 0.001
86      mlp                       M2  5000  e_otsu_cua_so_co_chan  0.911459     0.015617  0.987329  0.001484  0.911 ± 0.016  0.987 ± 0.001
87      mlp                       M2  5000         h_chong_sap_05  0.927313     0.003224  0.987329  0.001484  0.927 ± 0.003  0.987 ± 0.001
88      mlp                       M2  5000         h_chong_sap_10  0.917693     0.015199  0.987329  0.001484  0.918 ± 0.015  0.987 ± 0.001
89      mlp                       M2  5000         h_chong_sap_20  0.911459     0.015617  0.987329  0.001484  0.911 ± 0.016  0.987 ± 0.001
90      mlp         isolation_forest     0              a_co_dinh  0.473199     0.009140  0.684869  0.006648  0.473 ± 0.009  0.685 ± 0.007
91      mlp         isolation_forest     0  e_otsu_cua_so_co_chan  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
92      mlp         isolation_forest     0         h_chong_sap_05  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
93      mlp         isolation_forest     0         h_chong_sap_10  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
94      mlp         isolation_forest     0         h_chong_sap_20  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
95      mlp                  k0_TADP     0              a_co_dinh  0.558046     0.016319  0.552650  0.071685  0.558 ± 0.016  0.553 ± 0.072
96      mlp                  k0_TADP     0  e_otsu_cua_so_co_chan  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
97      mlp                  k0_TADP     0         h_chong_sap_05  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
98      mlp                  k0_TADP     0         h_chong_sap_10  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
99      mlp                  k0_TADP     0         h_chong_sap_20  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
100     mlp  k0_chon_kiem_dinh_nguon     0              a_co_dinh  0.550457     0.023040  0.561145  0.046670  0.550 ± 0.023  0.561 ± 0.047
101     mlp  k0_chon_kiem_dinh_nguon     0  e_otsu_cua_so_co_chan  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
102     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_05  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
103     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_10  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
104     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_20  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
105     mlp        k0_trung_binh_deu     0              a_co_dinh  0.495391     0.009734  0.523688  0.065174  0.495 ± 0.010  0.524 ± 0.065
106     mlp        k0_trung_binh_deu     0  e_otsu_cua_so_co_chan  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
107     mlp        k0_trung_binh_deu     0         h_chong_sap_05  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
108     mlp        k0_trung_binh_deu     0         h_chong_sap_10  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
109     mlp        k0_trung_binh_deu     0         h_chong_sap_20  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
110     mlp             tran_du_nhan    -1              a_co_dinh  0.959550     0.003465  0.997544  0.000044  0.960 ± 0.003  0.998 ± 0.000
111     mlp             tran_du_nhan    -1  e_otsu_cua_so_co_chan  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
112     mlp             tran_du_nhan    -1         h_chong_sap_05  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
113     mlp             tran_du_nhan    -1         h_chong_sap_10  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
114     mlp             tran_du_nhan    -1         h_chong_sap_20  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
115     mlp            tu_huan_luyen     0              a_co_dinh  0.533710     0.019008  0.580383  0.031880  0.534 ± 0.019  0.580 ± 0.032
116     mlp            tu_huan_luyen     0  e_otsu_cua_so_co_chan  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
117     mlp            tu_huan_luyen     0         h_chong_sap_05  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
118     mlp            tu_huan_luyen     0         h_chong_sap_10  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
119     mlp            tu_huan_luyen     0         h_chong_sap_20  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
120    tree                    CORAL     0              a_co_dinh  0.440268     0.013235  0.575131  0.122143  0.440 ± 0.013  0.575 ± 0.122
121    tree                    CORAL     0  e_otsu_cua_so_co_chan  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
122    tree                    CORAL     0         h_chong_sap_05  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
123    tree                    CORAL     0         h_chong_sap_10  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
124    tree                    CORAL     0         h_chong_sap_20  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
125    tree       DE_XUAT_dong_thuan     0              a_co_dinh  0.451046     0.027016  0.559176  0.035287  0.451 ± 0.027  0.559 ± 0.035
126    tree       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
127    tree       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
128    tree       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
129    tree       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
130    tree                       M2   100              a_co_dinh  0.764339     0.035173  0.826648  0.039985  0.764 ± 0.035  0.827 ± 0.040
131    tree                       M2   100  e_otsu_cua_so_co_chan  0.769730     0.031209  0.826648  0.039985  0.770 ± 0.031  0.827 ± 0.040
132    tree                       M2   100         h_chong_sap_05  0.768398     0.034931  0.826648  0.039985  0.768 ± 0.035  0.827 ± 0.040
133    tree                       M2   100         h_chong_sap_10  0.772516     0.035437  0.826648  0.039985  0.773 ± 0.035  0.827 ± 0.040
134    tree                       M2   100         h_chong_sap_20  0.770868     0.034413  0.826648  0.039985  0.771 ± 0.034  0.827 ± 0.040
135    tree                       M2   500              a_co_dinh  0.845513     0.030673  0.931702  0.008923  0.846 ± 0.031  0.932 ± 0.009
136    tree                       M2   500  e_otsu_cua_so_co_chan  0.845236     0.005664  0.931702  0.008923  0.845 ± 0.006  0.932 ± 0.009
137    tree                       M2   500         h_chong_sap_05  0.835904     0.034810  0.931702  0.008923  0.836 ± 0.035  0.932 ± 0.009
138    tree                       M2   500         h_chong_sap_10  0.818907     0.038728  0.931702  0.008923  0.819 ± 0.039  0.932 ± 0.009
139    tree                       M2   500         h_chong_sap_20  0.815492     0.035305  0.931702  0.008923  0.815 ± 0.035  0.932 ± 0.009
140    tree                       M2  1000              a_co_dinh  0.806968     0.043406  0.932180  0.028316  0.807 ± 0.043  0.932 ± 0.028
141    tree                       M2  1000  e_otsu_cua_so_co_chan  0.820031     0.024346  0.932180  0.028316  0.820 ± 0.024  0.932 ± 0.028

## Ô 3 – Tổng hợp và kiểm định (chạy bất cứ lúc nào, kể cả khi mới xong một phần)

- Bảng 15.1: Macro-F1 ± nửa khoảng tin cậy 95%; Bảng 15.2: AUROC ± nửa khoảng tin cậy 95%;
- Bảng 15.3: kiểm định Wilcoxon – ngưỡng h10 so với ngưỡng cố định;
- Bảng 15.4: kiểm định Wilcoxon – M2 với k nhãn so với cách không nhãn tốt nhất;
- Bảng 15.5: từng mạng; Bảng 15.6: độ nhạy mức chống sập; Bảng 15.7: số lần M2 không học được.

Chạy xong báo Claude.

In [4]:
import sys
from google.colab import drive
drive.mount("/content/drive")
sys.path.insert(0, "/content/drive/MyDrive/TADP_Q1/code")
for m in [k for k in sys.modules if k.startswith("tadp")]:
    del sys.modules[m]
from tadp.config import get_config
from tadp.final_run import summarize_final
B = "/content/drive/MyDrive/TADP_Q1"
cfg = get_config(RAW_DIR=f"{B}/raw_cic", CACHE_DIR=f"{B}/cache_cic", RESULT_DIR=f"{B}/results/b15_chot")
summarize_final(cfg)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Số hạt giống đã có: 5 ([np.int64(11), np.int64(22), np.int64(33), np.int64(44), np.int64(55)])

BẢNG 15.1 – Macro-F1 trung bình 4 mạng ± nửa khoảng tin cậy 95% (qua các hạt giống)
  a = ngưỡng cố định, h10 = chống sập 10% (cách chính); k = -1 là mốc đủ nhãn
 mo_hinh                                 lgbm                           mlp                          tree
cach_nguong                        a_co_dinh h_chong_sap_10      a_co_dinh h_chong_sap_10      a_co_dinh h_chong_sap_10
phuong_phap             k
CORAL                    0     0.443 ± 0.033  0.351 ± 0.042  0.413 ± 0.073  0.444 ± 0.055  0.440 ± 0.013  0.330 ± 0.039
DE_XUAT_dong_thuan       0     0.470 ± 0.025  0.471 ± 0.023  0.463 ± 0.066  0.476 ± 0.073  0.451 ± 0.027  0.466 ± 0.041
M2                       100   0.782 ± 0.057  0.785 ± 0.059  0.806 ± 0.019  0.799 ± 0.017  0.764 ± 0.035  0.773 ± 0.035
                         500   0.790 ± 0.020  0.826 ± 0.048  0.899 ± 0.007  0.895 ± 0.004  0.846 ± 0.031  0.819 ± 0.039
                         1000  0.840 ± 0.045  0.888 ± 0.041  0.917 ± 0.007  0.907 ± 0.004  0.807 ± 0.043  0.787 ± 0.054
                         5000  0.840 ± 0.029  0.922 ± 0.047  0.933 ± 0.004  0.918 ± 0.015  0.811 ± 0.020  0.797 ± 0.027
isolation_forest         0     0.473 ± 0.009  0.452 ± 0.041  0.473 ± 0.009  0.452 ± 0.041  0.473 ± 0.009  0.452 ± 0.041
k0_TADP                  0     0.505 ± 0.033  0.458 ± 0.034  0.558 ± 0.016  0.528 ± 0.045  0.500 ± 0.044  0.389 ± 0.069
k0_chon_kiem_dinh_nguon  0     0.499 ± 0.017  0.528 ± 0.052  0.550 ± 0.023  0.534 ± 0.038  0.540 ± 0.035  0.513 ± 0.047
k0_trung_binh_deu        0     0.447 ± 0.032  0.377 ± 0.031  0.495 ± 0.010  0.502 ± 0.039  0.441 ± 0.024  0.270 ± 0.095
tran_du_nhan            -1     0.971 ± 0.001  0.965 ± 0.008  0.960 ± 0.003  0.949 ± 0.003  0.965 ± 0.001  0.956 ± 0.001
tu_huan_luyen            0     0.519 ± 0.030  0.514 ± 0.028  0.534 ± 0.019  0.536 ± 0.020  0.443 ± 0.079  0.433 ± 0.075

BẢNG 15.2 – AUROC trung bình 4 mạng ± nửa khoảng tin cậy 95%
 mo_hinh                                 lgbm            mlp           tree
phuong_phap             k
CORAL                    0     0.529 ± 0.082  0.587 ± 0.061  0.575 ± 0.122
DE_XUAT_dong_thuan       0     0.588 ± 0.044  0.569 ± 0.078  0.559 ± 0.035
M2                       100   0.950 ± 0.011  0.903 ± 0.043  0.827 ± 0.040
                         500   0.980 ± 0.009  0.958 ± 0.016  0.932 ± 0.009
                         1000  0.989 ± 0.003  0.976 ± 0.006  0.932 ± 0.028
                         5000  0.995 ± 0.000  0.987 ± 0.001  0.880 ± 0.023
isolation_forest         0     0.685 ± 0.007  0.685 ± 0.007  0.685 ± 0.007
k0_TADP                  0     0.562 ± 0.037  0.553 ± 0.072  0.382 ± 0.059
k0_chon_kiem_dinh_nguon  0     0.561 ± 0.036  0.561 ± 0.047  0.564 ± 0.048
k0_trung_binh_deu        0     0.561 ± 0.019  0.524 ± 0.065  0.354 ± 0.060
tran_du_nhan            -1     0.998 ± 0.001  0.998 ± 0.000  0.997 ± 0.000
tu_huan_luyen            0     0.642 ± 0.023  0.580 ± 0.032  0.480 ± 0.102

BẢNG 15.3 – Kiểm định Wilcoxon: ngưỡng h10 so với ngưỡng cố định (M2)
  p_value < 0,05: chênh lệch khó là do may rủi
 mo_hinh    k  so_cap  trung_vi_chenh_lech  h10_hon  h10_kem  p_value
   lgbm  100      60               0.0000       15       18   0.9786
   lgbm  500      60               0.0001       30       29   0.3191
   lgbm 1000      60               0.0000       31       28   0.1273
   lgbm 5000      60              -0.0000       30       30   0.1152
    mlp  100      60               0.0000        6       25   0.0020
    mlp  500      60              -0.0020       19       37   0.0532
    mlp 1000      60              -0.0028       18       42   0.0008
    mlp 5000      60              -0.0017       20       40   0.0053
   tree  100      60               0.0000        7        7   0.3967
   tree  500      60               0.0000        5       29   0.0000
   tree 1000      60              -0.0051        5       33   0.0000
   tree 5000      60              -0.0072        7       44   0.0000

BẢNG 15.4 – Kiểm định Wilcoxon: M2 với k nhãn (h10) so với cách không nhãn tốt nhất
 mo_hinh     khong_nhan_tot_nhat    k  so_cap  trung_vi_chenh_lech  M2_hon  M2_kem  p_value
   lgbm k0_chon_kiem_dinh_nguon  100      20               0.2148      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon  500      20               0.2734      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon 1000      20               0.3950      20       0      0.0
   lgbm k0_chon_kiem_dinh_nguon 5000      20               0.4388      20       0      0.0
    mlp           tu_huan_luyen  100      20               0.2581      20       0      0.0
    mlp           tu_huan_luyen  500      20               0.3517      20       0      0.0
    mlp           tu_huan_luyen 1000      20               0.3783      20       0      0.0
    mlp           tu_huan_luyen 5000      20               0.3902      20       0      0.0
   tree k0_chon_kiem_dinh_nguon  100      20               0.2542      20       0      0.0
   tree k0_chon_kiem_dinh_nguon  500      20               0.2781      20       0      0.0
   tree k0_chon_kiem_dinh_nguon 1000      20               0.2594      20       0      0.0
   tree k0_chon_kiem_dinh_nguon 5000      20               0.2817      19       1      0.0

BẢNG 15.5 – Macro-F1 theo từng mạng (h10, trung bình các hạt giống)
 target                                 CIC-IDS2017  CIC-ToN-IoT  CIC-UNSW-NB15  CSE-CIC-IDS2018
mo_hinh phuong_phap             k
lgbm    CORAL                    0           0.355        0.384          0.360            0.304
        DE_XUAT_dong_thuan       0           0.578        0.423          0.496            0.388
        M2                       100         0.938        0.767          0.592            0.843
                                 500         0.971        0.600          0.785            0.950
                                 1000        0.979        0.797          0.813            0.964
                                 5000        0.991        0.882          0.837            0.976
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.685        0.375          0.390            0.384
        k0_chon_kiem_dinh_nguon  0           0.799        0.427          0.347            0.538
        k0_trung_binh_deu        0           0.486        0.388          0.313            0.323
        tran_du_nhan            -1           1.000        0.992          0.870            0.999
        tu_huan_luyen            0           0.720        0.387          0.515            0.435
mlp     CORAL                    0           0.671        0.377          0.347            0.381
        DE_XUAT_dong_thuan       0           0.554        0.601          0.362            0.386
        M2                       100         0.954        0.862          0.597            0.783
                                 500         0.974        0.935          0.754            0.916
                                 1000        0.982        0.937          0.794            0.914
                                 5000        0.988        0.956          0.819            0.907
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.730        0.497          0.438            0.446
        k0_chon_kiem_dinh_nguon  0           0.761        0.555          0.400            0.422
        k0_trung_binh_deu        0           0.659        0.463          0.438            0.447
        tran_du_nhan            -1           0.997        0.983          0.828            0.989
        tu_huan_luyen            0           0.753        0.590          0.363            0.436
tree    CORAL                    0           0.256        0.469          0.365            0.231
        DE_XUAT_dong_thuan       0           0.575        0.453          0.440            0.395
        M2                       100         0.919        0.764          0.580            0.828
                                 500         0.910        0.735          0.784            0.846
                                 1000        0.922        0.584          0.799            0.843
                                 5000        0.951        0.469          0.829            0.941
        isolation_forest         0           0.663        0.343          0.328            0.475
        k0_TADP                  0           0.464        0.336          0.427            0.327
        k0_chon_kiem_dinh_nguon  0           0.698        0.395          0.401            0.557
        k0_trung_binh_deu        0           0.218        0.349          0.320            0.193
        tran_du_nhan            -1           0.994        0.988          0.849            0.991
        tu_huan_luyen            0           0.539        0.332          0.442            0.419

BẢNG 15.6 – Độ nhạy: Macro-F1 theo cách đặt ngưỡng (a, e, h05, h10, h20)
 cach_nguong                 a_co_dinh  e_otsu_cua_so_co_chan  h_chong_sap_05  h_chong_sap_10  h_chong_sap_20
mo_hinh phuong_phap  k
lgbm    M2            100       0.782                  0.789           0.786           0.785           0.782
                      500       0.790                  0.838           0.794           0.826           0.831
                      1000      0.840                  0.910           0.861           0.888           0.917
                      5000      0.840                  0.935           0.903           0.922           0.938
        tran_du_nhan -1         0.971                  0.854           0.965           0.965           0.965
mlp     M2            100       0.806                  0.779           0.804           0.799           0.797
                      500       0.899                  0.856           0.897           0.895           0.883
                      1000      0.917                  0.888           0.913           0.907           0.895
                      5000      0.933                  0.911           0.927           0.918           0.911
        tran_du_nhan -1         0.960                  0.949           0.949           0.949           0.949
tree    M2            100       0.764                  0.770           0.768           0.773           0.771
                      500       0.846                  0.845           0.836           0.819           0.815
                      1000      0.807                  0.820           0.796           0.787           0.775
                      5000      0.811                  0.805           0.802           0.797           0.823
        tran_du_nhan -1         0.965                  0.955           0.956           0.956           0.955

BẢNG 15.7 – Số lần M2 không học được (< 3 luồng của một lớp)
 mo_hinh  k    target
lgbm     100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2
mlp      100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2
tree     100  CIC-UNSW-NB15      7
              CSE-CIC-IDS2018    2

    mo_hinh              phuong_phap     k            cach_nguong  macro_f1  macro_f1_ci     auroc  auroc_ci              o             oa
0      lgbm                    CORAL     0              a_co_dinh  0.442615     0.032912  0.529081  0.082000  0.443 ± 0.033  0.529 ± 0.082
1      lgbm                    CORAL     0  e_otsu_cua_so_co_chan  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
2      lgbm                    CORAL     0         h_chong_sap_05  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
3      lgbm                    CORAL     0         h_chong_sap_10  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
4      lgbm                    CORAL     0         h_chong_sap_20  0.350663     0.041545  0.529081  0.082000  0.351 ± 0.042  0.529 ± 0.082
5      lgbm       DE_XUAT_dong_thuan     0              a_co_dinh  0.469573     0.025202  0.588361  0.044033  0.470 ± 0.025  0.588 ± 0.044
6      lgbm       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
7      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
8      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
9      lgbm       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.471180     0.022580  0.588361  0.044033  0.471 ± 0.023  0.588 ± 0.044
10     lgbm                       M2   100              a_co_dinh  0.781625     0.056654  0.950019  0.011289  0.782 ± 0.057  0.950 ± 0.011
11     lgbm                       M2   100  e_otsu_cua_so_co_chan  0.788535     0.036946  0.950019  0.011289  0.789 ± 0.037  0.950 ± 0.011
12     lgbm                       M2   100         h_chong_sap_05  0.786247     0.054978  0.950019  0.011289  0.786 ± 0.055  0.950 ± 0.011
13     lgbm                       M2   100         h_chong_sap_10  0.784955     0.059032  0.950019  0.011289  0.785 ± 0.059  0.950 ± 0.011
14     lgbm                       M2   100         h_chong_sap_20  0.781771     0.057630  0.950019  0.011289  0.782 ± 0.058  0.950 ± 0.011
15     lgbm                       M2   500              a_co_dinh  0.790331     0.020056  0.979688  0.008789  0.790 ± 0.020  0.980 ± 0.009
16     lgbm                       M2   500  e_otsu_cua_so_co_chan  0.838291     0.066220  0.979688  0.008789  0.838 ± 0.066  0.980 ± 0.009
17     lgbm                       M2   500         h_chong_sap_05  0.794279     0.024298  0.979688  0.008789  0.794 ± 0.024  0.980 ± 0.009
18     lgbm                       M2   500         h_chong_sap_10  0.826411     0.047650  0.979688  0.008789  0.826 ± 0.048  0.980 ± 0.009
19     lgbm                       M2   500         h_chong_sap_20  0.830775     0.053787  0.979688  0.008789  0.831 ± 0.054  0.980 ± 0.009
20     lgbm                       M2  1000              a_co_dinh  0.840404     0.044615  0.989273  0.002548  0.840 ± 0.045  0.989 ± 0.003
21     lgbm                       M2  1000  e_otsu_cua_so_co_chan  0.909637     0.025759  0.989273  0.002548  0.910 ± 0.026  0.989 ± 0.003
22     lgbm                       M2  1000         h_chong_sap_05  0.861321     0.043337  0.989273  0.002548  0.861 ± 0.043  0.989 ± 0.003
23     lgbm                       M2  1000         h_chong_sap_10  0.888103     0.040608  0.989273  0.002548  0.888 ± 0.041  0.989 ± 0.003
24     lgbm                       M2  1000         h_chong_sap_20  0.916802     0.027822  0.989273  0.002548  0.917 ± 0.028  0.989 ± 0.003
25     lgbm                       M2  5000              a_co_dinh  0.840033     0.028780  0.994596  0.000325  0.840 ± 0.029  0.995 ± 0.000
26     lgbm                       M2  5000  e_otsu_cua_so_co_chan  0.934796     0.006572  0.994596  0.000325  0.935 ± 0.007  0.995 ± 0.000
27     lgbm                       M2  5000         h_chong_sap_05  0.903444     0.043384  0.994596  0.000325  0.903 ± 0.043  0.995 ± 0.000
28     lgbm                       M2  5000         h_chong_sap_10  0.921568     0.047103  0.994596  0.000325  0.922 ± 0.047  0.995 ± 0.000
29     lgbm                       M2  5000         h_chong_sap_20  0.938382     0.005630  0.994596  0.000325  0.938 ± 0.006  0.995 ± 0.000
30     lgbm         isolation_forest     0              a_co_dinh  0.473199     0.009140  0.684869  0.006648  0.473 ± 0.009  0.685 ± 0.007
31     lgbm         isolation_forest     0  e_otsu_cua_so_co_chan  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
32     lgbm         isolation_forest     0         h_chong_sap_05  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
33     lgbm         isolation_forest     0         h_chong_sap_10  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
34     lgbm         isolation_forest     0         h_chong_sap_20  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
35     lgbm                  k0_TADP     0              a_co_dinh  0.505021     0.032541  0.561930  0.036822  0.505 ± 0.033  0.562 ± 0.037
36     lgbm                  k0_TADP     0  e_otsu_cua_so_co_chan  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
37     lgbm                  k0_TADP     0         h_chong_sap_05  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
38     lgbm                  k0_TADP     0         h_chong_sap_10  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
39     lgbm                  k0_TADP     0         h_chong_sap_20  0.458469     0.034219  0.561930  0.036822  0.458 ± 0.034  0.562 ± 0.037
40     lgbm  k0_chon_kiem_dinh_nguon     0              a_co_dinh  0.498551     0.017400  0.561417  0.036276  0.499 ± 0.017  0.561 ± 0.036
41     lgbm  k0_chon_kiem_dinh_nguon     0  e_otsu_cua_so_co_chan  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
42     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_05  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
43     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_10  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
44     lgbm  k0_chon_kiem_dinh_nguon     0         h_chong_sap_20  0.527747     0.051705  0.561417  0.036276  0.528 ± 0.052  0.561 ± 0.036
45     lgbm        k0_trung_binh_deu     0              a_co_dinh  0.447383     0.031663  0.560953  0.019297  0.447 ± 0.032  0.561 ± 0.019
46     lgbm        k0_trung_binh_deu     0  e_otsu_cua_so_co_chan  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
47     lgbm        k0_trung_binh_deu     0         h_chong_sap_05  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
48     lgbm        k0_trung_binh_deu     0         h_chong_sap_10  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
49     lgbm        k0_trung_binh_deu     0         h_chong_sap_20  0.377417     0.030831  0.560953  0.019297  0.377 ± 0.031  0.561 ± 0.019
50     lgbm             tran_du_nhan    -1              a_co_dinh  0.970539     0.000602  0.998259  0.000590  0.971 ± 0.001  0.998 ± 0.001
51     lgbm             tran_du_nhan    -1  e_otsu_cua_so_co_chan  0.853685     0.119842  0.998259  0.000590  0.854 ± 0.120  0.998 ± 0.001
52     lgbm             tran_du_nhan    -1         h_chong_sap_05  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
53     lgbm             tran_du_nhan    -1         h_chong_sap_10  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
54     lgbm             tran_du_nhan    -1         h_chong_sap_20  0.965239     0.007958  0.998259  0.000590  0.965 ± 0.008  0.998 ± 0.001
55     lgbm            tu_huan_luyen     0              a_co_dinh  0.518978     0.029518  0.642075  0.023058  0.519 ± 0.030  0.642 ± 0.023
56     lgbm            tu_huan_luyen     0  e_otsu_cua_so_co_chan  0.514204     0.027782  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
57     lgbm            tu_huan_luyen     0         h_chong_sap_05  0.514220     0.027800  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
58     lgbm            tu_huan_luyen     0         h_chong_sap_10  0.514231     0.027815  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
59     lgbm            tu_huan_luyen     0         h_chong_sap_20  0.514204     0.027782  0.642075  0.023058  0.514 ± 0.028  0.642 ± 0.023
60      mlp                    CORAL     0              a_co_dinh  0.412621     0.073005  0.586801  0.060634  0.413 ± 0.073  0.587 ± 0.061
61      mlp                    CORAL     0  e_otsu_cua_so_co_chan  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
62      mlp                    CORAL     0         h_chong_sap_05  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
63      mlp                    CORAL     0         h_chong_sap_10  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
64      mlp                    CORAL     0         h_chong_sap_20  0.443858     0.055207  0.586801  0.060634  0.444 ± 0.055  0.587 ± 0.061
65      mlp       DE_XUAT_dong_thuan     0              a_co_dinh  0.462725     0.065899  0.568898  0.078224  0.463 ± 0.066  0.569 ± 0.078
66      mlp       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
67      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
68      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
69      mlp       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.475922     0.072668  0.568898  0.078224  0.476 ± 0.073  0.569 ± 0.078
70      mlp                       M2   100              a_co_dinh  0.806449     0.018885  0.903011  0.042607  0.806 ± 0.019  0.903 ± 0.043
71      mlp                       M2   100  e_otsu_cua_so_co_chan  0.778620     0.024352  0.903011  0.042607  0.779 ± 0.024  0.903 ± 0.043
72      mlp                       M2   100         h_chong_sap_05  0.804044     0.019321  0.903011  0.042607  0.804 ± 0.019  0.903 ± 0.043
73      mlp                       M2   100         h_chong_sap_10  0.799010     0.017103  0.903011  0.042607  0.799 ± 0.017  0.903 ± 0.043
74      mlp                       M2   100         h_chong_sap_20  0.797178     0.017553  0.903011  0.042607  0.797 ± 0.018  0.903 ± 0.043
75      mlp                       M2   500              a_co_dinh  0.898829     0.006687  0.957597  0.015985  0.899 ± 0.007  0.958 ± 0.016
76      mlp                       M2   500  e_otsu_cua_so_co_chan  0.856481     0.022044  0.957597  0.015985  0.856 ± 0.022  0.958 ± 0.016
77      mlp                       M2   500         h_chong_sap_05  0.896664     0.004713  0.957597  0.015985  0.897 ± 0.005  0.958 ± 0.016
78      mlp                       M2   500         h_chong_sap_10  0.894764     0.004496  0.957597  0.015985  0.895 ± 0.004  0.958 ± 0.016
79      mlp                       M2   500         h_chong_sap_20  0.883297     0.018366  0.957597  0.015985  0.883 ± 0.018  0.958 ± 0.016
80      mlp                       M2  1000              a_co_dinh  0.917136     0.006507  0.976010  0.005865  0.917 ± 0.007  0.976 ± 0.006
81      mlp                       M2  1000  e_otsu_cua_so_co_chan  0.887949     0.015345  0.976010  0.005865  0.888 ± 0.015  0.976 ± 0.006
82      mlp                       M2  1000         h_chong_sap_05  0.913403     0.006309  0.976010  0.005865  0.913 ± 0.006  0.976 ± 0.006
83      mlp                       M2  1000         h_chong_sap_10  0.906826     0.003890  0.976010  0.005865  0.907 ± 0.004  0.976 ± 0.006
84      mlp                       M2  1000         h_chong_sap_20  0.894816     0.016606  0.976010  0.005865  0.895 ± 0.017  0.976 ± 0.006
85      mlp                       M2  5000              a_co_dinh  0.933137     0.004405  0.987329  0.001484  0.933 ± 0.004  0.987 ± 0.001
86      mlp                       M2  5000  e_otsu_cua_so_co_chan  0.911459     0.015617  0.987329  0.001484  0.911 ± 0.016  0.987 ± 0.001
87      mlp                       M2  5000         h_chong_sap_05  0.927313     0.003224  0.987329  0.001484  0.927 ± 0.003  0.987 ± 0.001
88      mlp                       M2  5000         h_chong_sap_10  0.917693     0.015199  0.987329  0.001484  0.918 ± 0.015  0.987 ± 0.001
89      mlp                       M2  5000         h_chong_sap_20  0.911459     0.015617  0.987329  0.001484  0.911 ± 0.016  0.987 ± 0.001
90      mlp         isolation_forest     0              a_co_dinh  0.473199     0.009140  0.684869  0.006648  0.473 ± 0.009  0.685 ± 0.007
91      mlp         isolation_forest     0  e_otsu_cua_so_co_chan  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
92      mlp         isolation_forest     0         h_chong_sap_05  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
93      mlp         isolation_forest     0         h_chong_sap_10  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
94      mlp         isolation_forest     0         h_chong_sap_20  0.452270     0.040993  0.684869  0.006648  0.452 ± 0.041  0.685 ± 0.007
95      mlp                  k0_TADP     0              a_co_dinh  0.558046     0.016319  0.552650  0.071685  0.558 ± 0.016  0.553 ± 0.072
96      mlp                  k0_TADP     0  e_otsu_cua_so_co_chan  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
97      mlp                  k0_TADP     0         h_chong_sap_05  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
98      mlp                  k0_TADP     0         h_chong_sap_10  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
99      mlp                  k0_TADP     0         h_chong_sap_20  0.527716     0.045172  0.552650  0.071685  0.528 ± 0.045  0.553 ± 0.072
100     mlp  k0_chon_kiem_dinh_nguon     0              a_co_dinh  0.550457     0.023040  0.561145  0.046670  0.550 ± 0.023  0.561 ± 0.047
101     mlp  k0_chon_kiem_dinh_nguon     0  e_otsu_cua_so_co_chan  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
102     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_05  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
103     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_10  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
104     mlp  k0_chon_kiem_dinh_nguon     0         h_chong_sap_20  0.534410     0.038383  0.561145  0.046670  0.534 ± 0.038  0.561 ± 0.047
105     mlp        k0_trung_binh_deu     0              a_co_dinh  0.495391     0.009734  0.523688  0.065174  0.495 ± 0.010  0.524 ± 0.065
106     mlp        k0_trung_binh_deu     0  e_otsu_cua_so_co_chan  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
107     mlp        k0_trung_binh_deu     0         h_chong_sap_05  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
108     mlp        k0_trung_binh_deu     0         h_chong_sap_10  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
109     mlp        k0_trung_binh_deu     0         h_chong_sap_20  0.501914     0.038863  0.523688  0.065174  0.502 ± 0.039  0.524 ± 0.065
110     mlp             tran_du_nhan    -1              a_co_dinh  0.959550     0.003465  0.997544  0.000044  0.960 ± 0.003  0.998 ± 0.000
111     mlp             tran_du_nhan    -1  e_otsu_cua_so_co_chan  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
112     mlp             tran_du_nhan    -1         h_chong_sap_05  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
113     mlp             tran_du_nhan    -1         h_chong_sap_10  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
114     mlp             tran_du_nhan    -1         h_chong_sap_20  0.949365     0.003124  0.997544  0.000044  0.949 ± 0.003  0.998 ± 0.000
115     mlp            tu_huan_luyen     0              a_co_dinh  0.533710     0.019008  0.580383  0.031880  0.534 ± 0.019  0.580 ± 0.032
116     mlp            tu_huan_luyen     0  e_otsu_cua_so_co_chan  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
117     mlp            tu_huan_luyen     0         h_chong_sap_05  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
118     mlp            tu_huan_luyen     0         h_chong_sap_10  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
119     mlp            tu_huan_luyen     0         h_chong_sap_20  0.535597     0.020186  0.580383  0.031880  0.536 ± 0.020  0.580 ± 0.032
120    tree                    CORAL     0              a_co_dinh  0.440268     0.013235  0.575131  0.122143  0.440 ± 0.013  0.575 ± 0.122
121    tree                    CORAL     0  e_otsu_cua_so_co_chan  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
122    tree                    CORAL     0         h_chong_sap_05  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
123    tree                    CORAL     0         h_chong_sap_10  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
124    tree                    CORAL     0         h_chong_sap_20  0.330168     0.038947  0.575131  0.122143  0.330 ± 0.039  0.575 ± 0.122
125    tree       DE_XUAT_dong_thuan     0              a_co_dinh  0.451046     0.027016  0.559176  0.035287  0.451 ± 0.027  0.559 ± 0.035
126    tree       DE_XUAT_dong_thuan     0  e_otsu_cua_so_co_chan  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
127    tree       DE_XUAT_dong_thuan     0         h_chong_sap_05  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
128    tree       DE_XUAT_dong_thuan     0         h_chong_sap_10  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
129    tree       DE_XUAT_dong_thuan     0         h_chong_sap_20  0.465590     0.040945  0.559176  0.035287  0.466 ± 0.041  0.559 ± 0.035
130    tree                       M2   100              a_co_dinh  0.764339     0.035173  0.826648  0.039985  0.764 ± 0.035  0.827 ± 0.040
131    tree                       M2   100  e_otsu_cua_so_co_chan  0.769730     0.031209  0.826648  0.039985  0.770 ± 0.031  0.827 ± 0.040
132    tree                       M2   100         h_chong_sap_05  0.768398     0.034931  0.826648  0.039985  0.768 ± 0.035  0.827 ± 0.040
133    tree                       M2   100         h_chong_sap_10  0.772516     0.035437  0.826648  0.039985  0.773 ± 0.035  0.827 ± 0.040
134    tree                       M2   100         h_chong_sap_20  0.770868     0.034413  0.826648  0.039985  0.771 ± 0.034  0.827 ± 0.040
135    tree                       M2   500              a_co_dinh  0.845513     0.030673  0.931702  0.008923  0.846 ± 0.031  0.932 ± 0.009
136    tree                       M2   500  e_otsu_cua_so_co_chan  0.845236     0.005664  0.931702  0.008923  0.845 ± 0.006  0.932 ± 0.009
137    tree                       M2   500         h_chong_sap_05  0.835904     0.034810  0.931702  0.008923  0.836 ± 0.035  0.932 ± 0.009
138    tree                       M2   500         h_chong_sap_10  0.818907     0.038728  0.931702  0.008923  0.819 ± 0.039  0.932 ± 0.009
139    tree                       M2   500         h_chong_sap_20  0.815492     0.035305  0.931702  0.008923  0.815 ± 0.035  0.932 ± 0.009
140    tree                       M2  1000              a_co_dinh  0.806968     0.043406  0.932180  0.028316  0.807 ± 0.043  0.932 ± 0.028
141    tree                       M2  1000  e_otsu_cua_so_co_chan  0.820031     0.024346  0.932180  0.028316  0.820 ± 0.024  0.932 ± 0.028